"""empty message

Revision ID: 224f21817a35
Revises: 
Create Date: 2019-06-03 16:03:14.464000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224f21817a35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('IDNumber', sa.String(length=20), nullable=False),
    sa.Column('Name', sa.String(length=20), nullable=True),
    sa.Column('Number', sa.String(length=20), nullable=True),
    sa.Column('Status', sa.String(length=20), nullable=False),
    sa.Column('Address', sa.String(length=20), nullable=False),
    sa.Column('Addressee', sa.String(length=20), nullable=False),
    sa.Column('Tel', sa.String(length=20), nullable=False),
    sa.Column('Code', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('IDNumber'),
    sa.UniqueConstraint('IDNumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###
