"""empty message

Revision ID: 6b5d9f7ea54c
Revises: 224f21817a35
Create Date: 2019-06-03 16:12:30.797000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b5d9f7ea54c'
down_revision = '224f21817a35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('IDNumber', sa.String(length=20), nullable=False),
    sa.Column('Name', sa.String(length=20), nullable=True),
    sa.Column('Number', sa.String(length=20), nullable=True),
    sa.Column('Status', sa.String(length=20), nullable=True),
    sa.Column('Address', sa.String(length=20), nullable=True),
    sa.Column('Addressee', sa.String(length=20), nullable=True),
    sa.Column('Tel', sa.String(length=20), nullable=True),
    sa.Column('Code', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('IDNumber'),
    sa.UniqueConstraint('IDNumber')
    )
    op.drop_index('IDNumber', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('IDNumber', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('Number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('Status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('Address', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Addressee', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Tel', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Code', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('IDNumber'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_index('IDNumber', 'user', ['IDNumber'], unique=True)
    op.drop_table('User')
    # ### end Alembic commands ###
